[WIP] Bump airbnb version
getconversio/eslint-config-conversio pull request #6
Opened 2018-10-25 10:46 UTC by jmnsf

And eslint.

2018-10-26 09:43 UTC, jmnsf commented
@getconversio/developers ready for review

2018-11-28 14:01 UTC, RickCraig requested changes

2018-11-28 14:01 UTC, RickCraig commented on package.json
> +    "eslint": "^5.7.0"
```suggestion
    "eslint": "^5.9.0"
```

2018-11-28 14:51 UTC, RickCraig approved these changes

2018-11-28 14:52 UTC, merged